## variable definition

# Define hostnames of all nodes in the cluster
# Please configure name resolution in advance
clusterNode="hd01 hd02 hd03"

# Define the hostname to be configured synchronously
# Please configure name resolution in advance
synNode="hd02 hd03"

# Define the path or directory of the synchronized configuration file
synConf="/etc/nginx/nginx.conf /etc/nginx/conf.d/ /etc/nginx/public/ /etc/nginx/stream.d/ /etc/nginx/*.crt /etc/nginx/*.key"
