#!/bin/bash

## variable definition
source /etc/nginxtool/nginxtool.conf
containerName="mes-platform_nginx"

## check variable definition
if [ -z "$clusterNode" ]; then
  echo -e "\033[31mNot support empty variable \$clusterNode definition!\033[0m"
  exit 1
fi

if [ -z "$synNode" ]; then
  echo -e "\033[31mNot support empty variable \$synNode definition!\033[0m"
  exit 1
fi

if [ -z "$synConf" ]; then
  echo -e "\033[31mNot support empty variable \$synConf definition!\033[0m"
  exit 1
fi

## fouction
synconf() {
  for i in $synNode; do
    ping -c 1 $i &> /dev/null
    if [ $? -ne "0" ]; then
      echo -e "\033[31mSynchronized is not successfully of node $i, connection failure!\033[0m"
      continue
    fi
    for j in $synConf; do
      /usr/bin/rsync -avP --delete $j $i:$j &> /dev/null
      if [ $? -ne "0" ]; then
        echo -e "\033[31m$i: Synchronized is not successfully of $j\033[0m"
      else
        echo "$i: Synchronized is successfully of $j"
      fi
    done
  done
}

chkconf() {
  for i in $clusterNode; do
    echo "Check config of "$i","
    ping -c 1 $i &> /dev/null
    if [ $? -ne "0" ]; then
      echo -e "\033[31mCheck configure is not successfully of node $i, connection failure!\033[0m"
      continue
    fi
    for containerID in $(/usr/bin/ssh $i "docker container ls | grep '$containerName' | awk '{print \$1}'"); do
      /usr/bin/ssh $i "docker exec $containerID /etc/init.d/nginx configtest"
    done
  done
}

status() {
  for i in $clusterNode; do
    ping -c 1 $i &> /dev/null
    if [ $? -ne "0" ]; then
      echo -e "\033[31mCheck service status is not successfully of node $i, connection failure!\033[0m"
      continue
    fi
    for containerID in $(/usr/bin/ssh $i "docker container ls | grep '$containerName' | awk '{print \$1}'"); do
      /usr/bin/ssh $i "docker exec $containerID /etc/init.d/nginx status"
    done
  done
}

start() {
  echo "Please execute a command similar to the following on the Docker cluster management node:"
  echo /usr/bin/docker stack deploy -c /data/docker/yml/nginx-loadBalancing-stack.yml mes-platform
}

stop() {
  echo "Please execute a command similar to the following on the Docker cluster management node:"
  echo "/usr/bin/docker service ls | grep $containerName | awk '{print \$1}'"
  echo /usr/bin/docker docker service rm "xxxxxxxx"
}

reload() {
  for i in $clusterNode; do
    ping -c 1 $i &> /dev/null
    if [ $? -ne "0" ]; then
      echo -e "\033[31mReload service is not successfully of node $i, connection failure!\033[0m"
      continue
    fi
    echo "Reloading "$i"..."
    for containerID in $(/usr/bin/ssh $i "docker container ls | grep '$containerName' | awk '{print \$1}'"); do
      /usr/bin/ssh $i "docker exec $containerID /etc/init.d/nginx reload"
    done
  done
}

case "$1" in
  check)
    chkconf
    ;;
  status)
    status
    ;;
  start)
    start
    ;;
  stop)
    stop
    ;;
  reload)
    reload
    ;;
  restart)
    stop
    start
    ;;
  sync)
    synconf
    ;;
  *)
    echo $"Usage: $0 {check|status|start|stop|reload|restart|sync}"
    exit 1
esac

exit $?
